# Generated by Django 5.2.6 on 2025-12-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pass1', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('image', models.FileField(null=True, upload_to='uploads/users/')),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('alt_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('area', models.TextField(default='Local')),
                ('house', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=20, null=True)),
                ('p_name', models.CharField(max_length=100)),
                ('p_quantity', models.IntegerField(blank=True, null=True)),
                ('p_price', models.IntegerField()),
                ('p_image', models.FileField(blank=True, null=True, upload_to='uploads/Shoping/')),
                ('p_date', models.CharField(max_length=100)),
                ('shop_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('cust_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.address')),
            ],
        ),
    ]
