# Generated by Django 5.2.6 on 2025-12-23 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name as shown to customers.', max_length=100)),
                ('category', models.CharField(help_text='High-level category (e.g. Electronics, Fashion).', max_length=50)),
                ('des', models.TextField(blank=True, help_text='Optional short description about the company.', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Logo or brand image.', null=True, upload_to='companies/')),
                ('status', models.BooleanField(default=True, help_text='Active companies are visible and can be used for products.')),
                ('created_at', models.DateTimeField(blank=True, help_text='First time this company was created (set on first save).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name.', max_length=50)),
                ('price', models.FloatField(help_text='Current price of the product.')),
                ('category', models.CharField(blank=True, help_text='Copied from company category or set manually.', max_length=255, null=True)),
                ('des', models.CharField(help_text='Short description or key details.', max_length=255)),
                ('image', models.ImageField(help_text='Product image.', upload_to='uploads/products/')),
                ('quantity', models.IntegerField(blank=True, help_text='Available stock quantity.', null=True)),
                ('status', models.BooleanField(default=True, help_text='If False, product is hidden (soft-deleted / inactive).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this product was created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this product was updated.', null=True)),
                ('company', models.ForeignKey(help_text='Company/brand this product belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.companys')),
            ],
        ),
    ]
