# Generated by Django 5.2.6 on 2025-12-25 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name as shown to customers.', max_length=100)),
                ('category', models.CharField(help_text='High-level category (Electronics, Fashion, Grocery, etc.).', max_length=50)),
                ('des', models.TextField(blank=True, help_text='Optional company description or tagline.', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, help_text='Company logo or brand image (recommended: 200x200px).', null=True, upload_to='companies/%Y/%m/')),
                ('status', models.BooleanField(default=True, help_text='Active companies appear in product dropdowns.')),
                ('created_at', models.DateTimeField(blank=True, help_text='Timestamp of company creation.', null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name', 'category'], name='admins_comp_name_ecef4b_idx'), models.Index(fields=['status'], name='admins_comp_status_acb16f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name visible to customers.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price in ₹.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(blank=True, help_text='Product category (auto-copied from company).', max_length=100, null=True)),
                ('des', models.TextField(blank=True, help_text='Product description or specifications.', max_length=500)),
                ('image', models.ImageField(help_text='Main product image (recommended: 400x400px).', upload_to='products/%Y/%m/%d/')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, help_text='Current stock quantity (0 = out of stock).', null=True)),
                ('status', models.BooleanField(default=True, help_text='False = hidden from customers (soft delete).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Product creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('company', models.ForeignKey(blank=True, help_text='Brand/manufacturer of this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.companys')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'quantity'], name='admins_prod_status_5eae9e_idx'), models.Index(fields=['company', 'status'], name='admins_prod_company_67eb7d_idx'), models.Index(fields=['name'], name='admins_prod_name_b819cc_idx')],
            },
        ),
    ]
